client_ip: "0.0.0.0"
client_http_port: 8080
client_https_port: 8443
client_grpc_port: 50051
internal_grpc_port: 50052
client_tls_private_key: "/swir.CA.pem"
client_tls_certificate: "/demoCA/cacert.pem"

pubsub:
  kafka: []
  nats: []
  aws_kinesis: []
stores:  
  redis: []
  dynamodb: []

services:
  resolver:
    resolver_type: DynamoDb
    resolver_config:
      region : eu-west-1
      table: swir-service-discovery  
  resolve_services: []
  announce_services:
    - service_details:
        service_name: magazines
        domain: swir
        protocol: tcp
      client_url: "http://127.0.0.1:8090"
      
      


      
