language: rust
cache: cargo

rust:
  - stable
script:
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

jobs:
  fast_finish: true
