language: rust
cache: cargo

rust:
  - stable
  - nightly
script:
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
