[package]
name = "swir"
version = "0.2.5"
authors = ["Dawid Nowak <nowakd@gmail.com>"]
repository = "https://github.com/swir-rs/swir"
readme = "README.md"
license = "Apache-2.0"
description = "Sidecar Written in Rust"
keywords = ["sidecar", "rest", "messaging","cloudcomputing","kafka","nats","grpc"]
categories = ["sidecar","messaging","kafka","nats","grpc","cloudcomputing"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5"
futures = "=0.3"
futures-core= "=0.3"
futures-util = "=0.3"
futures-executor = "=0.3"

log = "0.4"
env_logger = "*"
color-backtrace="*"
rand = "*"
base64 = "*"

cfg-if = { version = "=0.1.10" }

tokio = { version = "=0.2", features = ["full","sync"]}
tokio-tls = "0.3"
tokio-rustls = "0.13"
rustls = "0.17"
async-stream = "0.2"
hyper = "0.13"
http = "0.2"   #hyper = { path = "../hyper" , features = ["runtime","stream"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }


rdkafka = { version="0.23" } #rdkafka = { version="0.23.1", path = "../rust-rdkafka" }
rdkafka-sys = { version = "1.3", default-features = false} #rdkafka-sys = { version = "1.3.1", default-features = false,path = "../rust-rdkafka/rdkafka-sys"}
nats = {version="*",optional=true}

rusoto_kinesis={ version="0.43"}
rusoto_dynamodb={ version="0.43"}
rusoto_signature={ version="0.43"}
rusoto_core={ version="0.43"}
aws-lock-client = {version="*", git="https://github.com/swir-rs/aws-lock-client-rs"} 
#aws-lock-client = {version="*", path="../aws-lock-client-rs"}
regex ="*"
lazy_static="*"

async-trait="*"
prost = "0.6"
prost-derive = "0.6"
tonic = {version="0.1", optional=false} #tonic = {version="0.1.1", path ="../tonic/tonic", optional=false}
config = { version="*", features = ["with_env_vars"],  git = "https://github.com/swir-rs/config-rs" } #config = { version="*", path = "../config-rs", features = ["with_env_vars"],  git = "https://github.com/swir-rs/config-rs" }
redis = { version="0.15",features = ["cluster"]}

[build-dependencies]
tonic-build = { version="0.1" } #tonic-build = { version="0.1.1-alpha.6", path ="../tonic/tonic-build" }

[features]
with_nats = ["nats"]
