client_ip: "0.0.0.0"
client_http_port: 8080
client_https_port: 8443
client_grpc_port: 50051
internal_grpc_port: 50052
client_tls_private_key: "/swir.CA.pem"
client_tls_certificate: "/demoCA/cacert.pem"
#client_executable: "client.jar"
pubsub:
  kafka: []
  nats: []
  aws_kinesis:
    - regions:
        - "eu-west-1"
      consumer_topics:       
        - consumer_topic: aws_processor_billing_blue
          consumer_group: swir
          client_topic: billing
      producer_topics:
        - producer_topic: aws_sink_green
          client_topic: shipments
stores:  
  redis: []
  dynamodb: []


services:  
  resolve_services: []
  announce_services: []


