client_ip: "0.0.0.0"
client_http_port: 8080
client_https_port: 8443
client_grpc_port: 50051
client_tls_private_key: "/swir.CA.pem"
client_tls_certificate: "/demoCA/cacert.pem"
#client_executable: "client.jar"
channels:
  kafka: []
  nats: []
  aws_kinesis:
    - regions:
        - "eu-west-1"
      consumer_topics:       
        - consumer_topic: aws_sink_green
          consumer_group: swir
          client_topic: shipments
      producer_topics: []
  
