version: '3.7'
# Sidecars layer. All sidecars are already deployed.
services:
  swir-example-configurator:
    networks:
      - swir-net
    image: swir-example-configurator:v2
    command: ["/bin/bash","-c","cp /config/* swir_config/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 1 
# Java gRCP
  order-generator-sidecar:
    networks:
      - swir-net
    image: swir:v2
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 2     
# python gRPC
  order-processor-sidecar:
    networks:
      - swir-net
    image: swir:v2
    depends_on:
      - swir-example-configurator
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_1.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 3           
# Java SpringBoot and REST        
  inventory-processor-sidecar:
    networks:
      - swir-net
    image: swir:v2
    depends_on:
      - swir-example-configurator
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_2.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 4           
# python gRPC              
  billing-processor-sidecar:
    networks:
      - swir-net
    image: swir:v2
    depends_on:
      - swir-example-configurator
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_3.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 5
# Python gRPC
  shipments-sink-sidecar:
    networks:
      - swir-net
    image: swir:v2
    depends_on:
      - swir-example-configurator
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_sink.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config                
        
volumes:
  swir_config:
networks:
  swir-net:
    external:
      name: docker_swir-net
