client_ip: "0.0.0.0"
client_http_port: 8080
client_https_port: 8443
client_grpc_port: 50051
internal_grpc_port: 50052
client_tls_private_key: "/swir.CA.pem"
client_tls_certificate: "/demoCA/cacert.pem"
#client_executable: "client.jar"
pubsub:
  kafka:
    - brokers: [kafka:9094]
      producer_topics:
        - producer_topic: processor1_kafka_blue
          client_topic: orders
      consumer_topics: []
  nats:
    - brokers:
        - nats://nats:4222
      consumer_topics: []
      producer_topics: []
      
  aws_kinesis: []
stores:  
  redis:
    - nodes: [redis://redis:6379/]
      tables:
        - table_name: "swir-demo"
          client_name: "source_store"
  dynamodb: []
      
