client_ip: "0.0.0.0"
client_http_port: 8080
client_https_port: 8443
client_grpc_port: 50051
client_tls_private_key: "/swir.CA.pem"
client_tls_certificate: "/demoCA/cacert.pem"
#client_executable: "client.jar"
pubsub:
  kafka:
    - brokers: [kafka:9094]
      consumer_topics:
        - consumer_topic: sink1_kafka_green
          consumer_group: swir
          client_topic: shipments
      producer_topics: []
  nats:
    - brokers:
        - nats://nats:4222
      consumer_topics: []
      producer_topics: []

  aws_kinesis: []

stores:  
  redis:
    - nodes: [redis://redis:6379/]
      tables:
        - table_name: "swir-demo"
          client_name: "sink_store"
  dynamodb: []
